#
# MIT License
#
# Copyright (c) 2021 NestedApi Project
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
version: "3.6"
services:
  # Azure SQL Database container
  azuresqledge:
    cap_add:
      - SYS_PTRACE
    container_name: azuresqledge
    restart: always
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=YnZekurEp4SZW0rd
    image: mcr.microsoft.com/azure-sql-edge
    networks:
      - internal-network
    ports:
      - 1433:1433/tcp
    user: mssql

  # Bus Message Service
  rabbitmq:
    command:
      - rabbitmq-server
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=YnZekurEp4SZW0rd
      - RABBITMQ_DEFAULT_VHOST=nested
    image: rabbitmq:alpine
    networks:
      - internal-network

  # Specific Module Service - Users
  users-service:
    container_name: users-service
    restart: always
    environment:
      - LOGIN_KEY=9HJYtLJTc7QEQ1ucAa84+GEIBzyyCkjj01L7l+UZ6QYPvhT3QF3MIcE43EXm6gOvZanU/mLGmEm4NIzwN+jq82AVAXQ5RsSYhnmMaQlOyyYSk9H+2UZldzlusR/2OutUnBuI4vBME/6eRMriLZYYio+1TXkDjvQdWwECEU99UYTZ/1gQCYckGEINMj0LnP65uwIPlKKt4XCmJijBAmVtgH1W876ypLxgIzDmHA==
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:sqlserver://azuresqledge:1433;databaseName=tempdb
      - QUARKUS_DATASOURCE_USERNAME=sa
      - QUARKUS_DATASOURCE_PASSWORD=YnZekurEp4SZW0rd
      - RABBITMQ_AMQP_URI=amqp://root:YnZekurEp4SZW0rd@rabbitmq:5672/nested
    build: ./src/Users
    networks:
      internal-network:
        aliases:
          - rabbitmq
          - azuresqledge
    user: daemon

  # Specific Module Service - Authentication
  auth-service:
    container_name: auth-service
    restart: always
    environment:
      - QUARKUS_DATASOURCE_USERNAME=sa
      - QUARKUS_DATASOURCE_PASSWORD=YnZekurEp4SZW0rd
      - RABBITMQ_AMQP_URI=amqp://root:YnZekurEp4SZW0rd@rabbitmq:5672/nested
      - LOGIN_KEY=9HJYtLJTc7QEQ1ucAa84+GEIBzyyCkjj01L7l+UZ6QYPvhT3QF3MIcE43EXm6gOvZanU/mLGmEm4NIzwN+jq82AVAXQ5RsSYhnmMaQlOyyYSk9H+2UZldzlusR/2OutUnBuI4vBME/6eRMriLZYYio+1TXkDjvQdWwECEU99UYTZ/1gQCYckGEINMj0LnP65uwIPlKKt4XCmJijBAmVtgH1W876ypLxgIzDmHA==
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:sqlserver://azuresqledge:1433;databaseName=tempdb
    build: ./src/Authentication
    networks:
      internal-network:
        aliases:
          - rabbitmq
          - azuresqledge
    user: daemon

  # NGINX Server as a API Gateway
  api-gateway:
    container_name: api-gateway
    restart: always
    image: nginx:stable-alpine
    environment:
      - NGINX_PORT=80
    volumes:
      - type: bind
        source: ./config/nginx/api-containers.conf
        target: /etc/nginx/conf.d/api-containers.conf
        read_only: true
      - type: bind
        source: ./config/nginx/api-endpoints.conf
        target: /etc/nginx/conf.d/api-endpoints.conf
        read_only: true
    networks:
      internal-network:
        aliases:
          - users-service
          - auth-service
    ports:
      - 8080:8080/tcp
networks:
  internal-network:
    external: false
