---
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  global-config
spec:
  config:
    # In the case of the server don't response correctly, we try to resend the petition.
    retry_policy:
      retry_on: "5xx"
    # In the case of the keep without response, we break the connection.
    circuit_breakers:
      max_retries: 3
      max_pending_requests: 2048
    # Policies for keepalive the connections.
    keepalive:
      time: 2
      interval: 2
      probes: 100
    # Policies for load balancing.
    load_balancer:
      policy: round_robin
    # Policies for secures request.
    requestPolicy:
      insecure:
        action: Redirect
    # Autosigning certificate.
    acmeProvider:
      email: user@example.com # Please, change me.
    tlsSecret:
      name: tls-cert
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  users-service
spec:
  # Related user service with its corresponding endpoint.
  prefix: /users/
  service: http://users-service:8080
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  payments-service
spec:
  # Related payments service with its corresponding endpoint
  prefix: /payments/
  service: http://payments-service:8080
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  invoices-service
spec:
  # Related invoices service with its corresponding endpoint
  prefix: /invoices/
  service: http://invoices-service:8080