/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.neirth.nestedapi.Invoices.Schemas;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Request extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8300349382312774796L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Request\",\"namespace\":\"io.neirth.nestedapi.Invoices.Schemas\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"invoice\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"InvoiceObj\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"userId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"creationDate\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"deliveryAddress\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"deliveryPostcode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"deliveryCountry\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"deliveryCurrency\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"deliveryAddressInformation\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"products\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ProductObj\",\"fields\":[{\"name\":\"productName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"productPrice\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"productAmount\",\"type\":[\"null\",\"int\"],\"default\":null}]}}],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Request> ENCODER =
      new BinaryMessageEncoder<Request>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Request> DECODER =
      new BinaryMessageDecoder<Request>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Request> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Request> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Request> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Request>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Request to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Request from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Request instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Request fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private io.neirth.nestedapi.Invoices.Schemas.InvoiceObj invoice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Request() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param invoice The new value for invoice
   */
  public Request(java.lang.CharSequence id, io.neirth.nestedapi.Invoices.Schemas.InvoiceObj invoice) {
    this.id = id;
    this.invoice = invoice;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return invoice;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: invoice = (io.neirth.nestedapi.Invoices.Schemas.InvoiceObj)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'invoice' field.
   * @return The value of the 'invoice' field.
   */
  public io.neirth.nestedapi.Invoices.Schemas.InvoiceObj getInvoice() {
    return invoice;
  }


  /**
   * Sets the value of the 'invoice' field.
   * @param value the value to set.
   */
  public void setInvoice(io.neirth.nestedapi.Invoices.Schemas.InvoiceObj value) {
    this.invoice = value;
  }

  /**
   * Creates a new Request RecordBuilder.
   * @return A new Request RecordBuilder
   */
  public static io.neirth.nestedapi.Invoices.Schemas.Request.Builder newBuilder() {
    return new io.neirth.nestedapi.Invoices.Schemas.Request.Builder();
  }

  /**
   * Creates a new Request RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Request RecordBuilder
   */
  public static io.neirth.nestedapi.Invoices.Schemas.Request.Builder newBuilder(io.neirth.nestedapi.Invoices.Schemas.Request.Builder other) {
    if (other == null) {
      return new io.neirth.nestedapi.Invoices.Schemas.Request.Builder();
    } else {
      return new io.neirth.nestedapi.Invoices.Schemas.Request.Builder(other);
    }
  }

  /**
   * Creates a new Request RecordBuilder by copying an existing Request instance.
   * @param other The existing instance to copy.
   * @return A new Request RecordBuilder
   */
  public static io.neirth.nestedapi.Invoices.Schemas.Request.Builder newBuilder(io.neirth.nestedapi.Invoices.Schemas.Request other) {
    if (other == null) {
      return new io.neirth.nestedapi.Invoices.Schemas.Request.Builder();
    } else {
      return new io.neirth.nestedapi.Invoices.Schemas.Request.Builder(other);
    }
  }

  /**
   * RecordBuilder for Request instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Request>
    implements org.apache.avro.data.RecordBuilder<Request> {

    private java.lang.CharSequence id;
    private io.neirth.nestedapi.Invoices.Schemas.InvoiceObj invoice;
    private io.neirth.nestedapi.Invoices.Schemas.InvoiceObj.Builder invoiceBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.neirth.nestedapi.Invoices.Schemas.Request.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.invoice)) {
        this.invoice = data().deepCopy(fields()[1].schema(), other.invoice);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasInvoiceBuilder()) {
        this.invoiceBuilder = io.neirth.nestedapi.Invoices.Schemas.InvoiceObj.newBuilder(other.getInvoiceBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Request instance
     * @param other The existing instance to copy.
     */
    private Builder(io.neirth.nestedapi.Invoices.Schemas.Request other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.invoice)) {
        this.invoice = data().deepCopy(fields()[1].schema(), other.invoice);
        fieldSetFlags()[1] = true;
      }
      this.invoiceBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.neirth.nestedapi.Invoices.Schemas.Request.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.neirth.nestedapi.Invoices.Schemas.Request.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'invoice' field.
      * @return The value.
      */
    public io.neirth.nestedapi.Invoices.Schemas.InvoiceObj getInvoice() {
      return invoice;
    }


    /**
      * Sets the value of the 'invoice' field.
      * @param value The value of 'invoice'.
      * @return This builder.
      */
    public io.neirth.nestedapi.Invoices.Schemas.Request.Builder setInvoice(io.neirth.nestedapi.Invoices.Schemas.InvoiceObj value) {
      validate(fields()[1], value);
      this.invoiceBuilder = null;
      this.invoice = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'invoice' field has been set.
      * @return True if the 'invoice' field has been set, false otherwise.
      */
    public boolean hasInvoice() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'invoice' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.neirth.nestedapi.Invoices.Schemas.InvoiceObj.Builder getInvoiceBuilder() {
      if (invoiceBuilder == null) {
        if (hasInvoice()) {
          setInvoiceBuilder(io.neirth.nestedapi.Invoices.Schemas.InvoiceObj.newBuilder(invoice));
        } else {
          setInvoiceBuilder(io.neirth.nestedapi.Invoices.Schemas.InvoiceObj.newBuilder());
        }
      }
      return invoiceBuilder;
    }

    /**
     * Sets the Builder instance for the 'invoice' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public io.neirth.nestedapi.Invoices.Schemas.Request.Builder setInvoiceBuilder(io.neirth.nestedapi.Invoices.Schemas.InvoiceObj.Builder value) {
      clearInvoice();
      invoiceBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'invoice' field has an active Builder instance
     * @return True if the 'invoice' field has an active Builder instance
     */
    public boolean hasInvoiceBuilder() {
      return invoiceBuilder != null;
    }

    /**
      * Clears the value of the 'invoice' field.
      * @return This builder.
      */
    public io.neirth.nestedapi.Invoices.Schemas.Request.Builder clearInvoice() {
      invoice = null;
      invoiceBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Request build() {
      try {
        Request record = new Request();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (invoiceBuilder != null) {
          try {
            record.invoice = this.invoiceBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("invoice"));
            throw e;
          }
        } else {
          record.invoice = fieldSetFlags()[1] ? this.invoice : (io.neirth.nestedapi.Invoices.Schemas.InvoiceObj) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Request>
    WRITER$ = (org.apache.avro.io.DatumWriter<Request>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Request>
    READER$ = (org.apache.avro.io.DatumReader<Request>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.id);
    }

    if (this.invoice == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.invoice.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.invoice = null;
      } else {
        if (this.invoice == null) {
          this.invoice = new io.neirth.nestedapi.Invoices.Schemas.InvoiceObj();
        }
        this.invoice.customDecode(in);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.invoice = null;
          } else {
            if (this.invoice == null) {
              this.invoice = new io.neirth.nestedapi.Invoices.Schemas.InvoiceObj();
            }
            this.invoice.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










