graph LR
	A((Client Device)) <--> | HTTP/HTTPS Request | B(API Gateway)

	K(Message Broker) --- C
  K(Message Broker) --- E
  K(Message Broker) --- G
	K(Message Broker) --- I

  subgraph "Endpoint Containers"
	B --> C(/auth)
  B --> E(/users)
  B --> G(/invoices)
  B --> I(/payments)
	end

  subgraph "Per-service Databases"
  C <--> D([Specific Database])
  E <--> F([Specific Database])
  G <--> H([Specific Database])
  I <--> J([Specific Database])
  end  

	L(Cache Service) --- C
  L(Cache Service) --- E
  L(Cache Service) --- G
  L(Cache Service) --- I
