graph LR
A((Client Device)) <--> | HTTP/HTTPS Request | B(API Gateway)

K(Message Broker) --- C
K(Message Broker) --- E
K(Message Broker) --- G

subgraph "Endpoint Containers"
    B --> C(/auth)
    B --> E(/users)
    B --> G(/invoices)
end

subgraph "Per-service Databases"
    C <--> F([Specific Database])
    E <--> H([Specific Database])
end 

subgraph "XML-RPC Channel"
    G <--> T([ERP Database])
end 

L(Cache Service) --- C
L(Cache Service) --- E
L(Cache Service) --- G